version: '3'
services:
    app_python:
        build: app_python/
        ports:
            - "5000"

    web:
        image: nginx
        ports:
            - "5000:80"
        volumes:
            - './web/nginx.conf:/etc/nginx/nginx.conf'
